### ISSUE TITLE
Colors are not rendering 

### ISSUE THREAD

**Issue by AlenaNik** [divriots/starter-tailwindcss#9]
<img width="1288" alt="Screenshot 2021-09-15 at 14 17 20" src="https://user-images.githubusercontent.com/38886707/133431819-138b520e-6f00-4de2-8ebb-2fe471e03098.png">
<img width="455" alt="Screenshot 2021-09-15 at 14 18 03" src="https://user-images.githubusercontent.com/38886707/133431914-1e4bb456-efa7-4a31-b7d3-dfbc57464b46.png">
Hey team,
I currently trying Tailwind CSS Design system, however, colors are not working for me. Adding screenshots if its helpful 🙂

**Comment by mveres** [comment]
This issue is fixed now, go ahead and give it a try @AlenaNik

**Comment by gqio** [comment]
Hi @AlenaNik ,

It's fixed on our side, please reopen if you still encounter the issue.

Best,

**Comment by AlenaNik** [comment]
Thanks guys! You are amazing! All works 👏
<img width="894" alt="Screenshot 2021-09-16 at 08 37 18" src="https://user-images.githubusercontent.com/38886707/133562187-68e9ead0-7da4-4e25-bda8-2ff1ece69efb.png">
